import { hashPassword } from './auth'
import type { CMSData } from './types'

function nowMinusHours(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString()
}

export function createSeedData(): CMSData {
  const now = new Date().toISOString()

  const adminId = 'user-admin'
  const editorId = 'user-editor'
  const authorId = 'user-author'
  const moderatorId = 'user-moderator'

  return {
    users: [
      {
        id: adminId,
        name: 'Администратор Эхо Алматы',
        email: 'admin@echoalmaty.local',
        role: 'admin',
        passwordHash: hashPassword('admin123'),
        active: true,
        avatar: '/placeholder-user.jpg',
        bio: {
          ru: 'Отвечает за платформу, пользователей и публикационный цикл.',
          kk: 'Платформаға, пайдаланушыларға және жариялау цикліне жауап береді.',
        },
        createdAt: now,
        updatedAt: now,
        lastLoginAt: null,
      },
      {
        id: editorId,
        name: 'Редактор Эхо Алматы',
        email: 'editor@echoalmaty.local',
        role: 'editor',
        passwordHash: hashPassword('editor123'),
        active: true,
        avatar: '/placeholder-user.jpg',
        bio: {
          ru: 'Проверяет материалы авторов и выпускает их в ленту.',
          kk: 'Авторлардың материалдарын тексеріп, лентаға шығарады.',
        },
        createdAt: now,
        updatedAt: now,
        lastLoginAt: null,
      },
      {
        id: authorId,
        name: 'Журналист Эхо Алматы',
        email: 'author@echoalmaty.local',
        role: 'author',
        passwordHash: hashPassword('author123'),
        active: true,
        avatar: '/placeholder-user.jpg',
        bio: {
          ru: 'Пишет репортажи, новости и интервью.',
          kk: 'Репортаждар, жаңалықтар және сұхбаттар жазады.',
        },
        createdAt: now,
        updatedAt: now,
        lastLoginAt: null,
      },
      {
        id: moderatorId,
        name: 'Модератор Эхо Алматы',
        email: 'moderator@echoalmaty.local',
        role: 'moderator',
        passwordHash: hashPassword('moderator123'),
        active: true,
        avatar: '/placeholder-user.jpg',
        bio: {
          ru: 'Следит за очередью публикаций и качеством материалов.',
          kk: 'Жарияланым кезегі мен материал сапасын қадағалайды.',
        },
        createdAt: now,
        updatedAt: now,
        lastLoginAt: null,
      },
    ],
    articles: [
      {
        id: 'article-astana-summit',
        slug: 'astana-summit-investments',
        title: {
          ru: 'В Астане открылся международный саммит по привлечению инвестиций',
          kk: 'Астанада инвестиция тартуға арналған халықаралық саммит ашылды',
        },
        excerpt: {
          ru: 'Делегации из более чем 30 стран обсуждают развитие транспортных коридоров и зеленой энергетики.',
          kk: '30-дан астам елдің делегациясы көлік дәліздері мен жасыл энергетиканы талқылап жатыр.',
        },
        body: {
          ru: 'В столице стартовал международный саммит, посвященный инвестициям, логистике и промышленной кооперации.\n\nПо словам организаторов, в рамках форума ожидаются соглашения по транспортной инфраструктуре, цифровым сервисам и энергетическим проектам.\n\nРедакция следит за итогами переговоров и обновит материал после пленарной сессии.',
          kk: 'Елордада инвестиция, логистика және өнеркәсіптік кооперацияға арналған халықаралық саммит басталды.\n\nҰйымдастырушылардың айтуынша, форум аясында көлік инфрақұрылымы, цифрлық сервистер және энергетикалық жобалар бойынша келісімдер күтіледі.\n\nРедакция пленарлық сессиядан кейін материалды жаңартады.',
        },
        seoTitle: {
          ru: 'Саммит в Астане: инвестиции, логистика и энергетика',
          kk: 'Астанадағы саммит: инвестиция, логистика және энергетика',
        },
        seoDescription: {
          ru: 'Главные темы международного саммита в Астане и его влияние на экономику Казахстана.',
          kk: 'Астанадағы халықаралық саммиттің негізгі тақырыптары және оның Қазақстан экономикасына әсері.',
        },
        mainImage: '/news/politics-astana.png',
        gallery: ['/news/politics-astana.png', '/news/economy-tenge.png'],
        videoUrls: ['https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
        authorId,
        reviewerId: editorId,
        categories: ['politics', 'business-economy'],
        tags: ['инвестиции', 'саммит', 'астана'],
        sourceName: 'Собственный корреспондент',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: true,
        breaking: true,
        views: 12480,
        readMinutes: 4,
        createdAt: nowMinusHours(20),
        updatedAt: nowMinusHours(2),
        submittedAt: nowMinusHours(5),
        reviewedAt: nowMinusHours(4),
        publishedAt: nowMinusHours(4),
        scheduledAt: null,
        deletedAt: null,
        revision: 3,
      },
      {
        id: 'article-rate',
        slug: 'tenge-exchange-rate-update',
        title: {
          ru: 'Национальный банк сохранил базовую ставку на прежнем уровне',
          kk: 'Ұлттық банк базалық мөлшерлемені бұрынғы деңгейде сақтады',
        },
        excerpt: {
          ru: 'Регулятор связал решение со стабилизацией инфляции и сдержанным ростом деловой активности.',
          kk: 'Реттеуші шешімді инфляцияның тұрақтануымен және іскерлік белсенділіктің баяу өсуімен байланыстырды.',
        },
        body: {
          ru: 'Национальный банк оставил базовую ставку без изменений после июльского заседания.\n\nФинансовый рынок ожидал именно такого решения, а аналитики считают, что цикл смягчения начнется не раньше следующего квартала.',
          kk: 'Ұлттық банк шілдедегі отырыстан кейін базалық мөлшерлемені өзгеріссіз қалдырды.\n\nҚаржы нарығы дәл осындай шешімді күткен, ал сарапшылар жұмсарту циклі келесі тоқсаннан ерте басталмайды деп есептейді.',
        },
        seoTitle: {
          ru: 'Базовая ставка в Казахстане осталась без изменений',
          kk: 'Қазақстанда базалық мөлшерлеме өзгеріссіз қалды',
        },
        seoDescription: {
          ru: 'Что означает решение Национального банка по базовой ставке для бизнеса и населения.',
          kk: 'Ұлттық банктің базалық мөлшерлеме бойынша шешімі бизнес пен халық үшін нені білдіреді.',
        },
        mainImage: '/news/economy-tenge.png',
        gallery: ['/news/economy-tenge.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['business-economy', 'analytics'],
        tags: ['ставка', 'инфляция', 'нацбанк'],
        sourceName: 'Национальный банк',
        sourceUrl: 'https://nationalbank.kz',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 8730,
        readMinutes: 3,
        createdAt: nowMinusHours(26),
        updatedAt: nowMinusHours(6),
        submittedAt: nowMinusHours(8),
        reviewedAt: nowMinusHours(7),
        publishedAt: nowMinusHours(7),
        scheduledAt: null,
        deletedAt: null,
        revision: 2,
      },
      {
        id: 'article-metro',
        slug: 'almaty-new-metro-line',
        title: {
          ru: 'В Алматы открыли новые станции метро — как изменится движение',
          kk: 'Алматыда метроның жаңа станциялары ашылды — қозғалыс қалай өзгереді',
        },
        excerpt: {
          ru: 'Продление линии должно разгрузить центральные улицы и связать спальные районы с деловым центром.',
          kk: 'Желінің ұзартылуы орталық көшелерді босатып, тұрғын аудандарды іскерлік орталықпен байланыстырады.',
        },
        body: {
          ru: 'В Алматы открыли новые станции метро, которые должны перераспределить пассажиропоток в час пик.\n\nГородские службы ожидают, что продление линии снизит нагрузку на магистрали и ускорит движение общественного транспорта.',
          kk: 'Алматыда жолаушылар ағынын қайта бөлетін метроның жаңа станциялары ашылды.\n\nҚалалық қызметтер желінің ұзартылуы магистральдардағы жүктемені азайтады және қоғамдық көліктің қозғалысын жылдамдатады деп күтеді.',
        },
        seoTitle: {
          ru: 'Новые станции метро в Алматы: что изменится',
          kk: 'Алматыдағы жаңа метро станциялары: не өзгереді',
        },
        seoDescription: {
          ru: 'Подробности об открытии новых станций метро и влиянии на городской трафик.',
          kk: 'Жаңа метро станцияларының ашылуы және оның қалалық трафикке әсері туралы толық мәлімет.',
        },
        mainImage: '/news/society-almaty.png',
        gallery: ['/news/society-almaty.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['society'],
        tags: ['алматы', 'метро', 'транспорт'],
        sourceName: '',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 15920,
        readMinutes: 3,
        createdAt: nowMinusHours(30),
        updatedAt: nowMinusHours(10),
        submittedAt: nowMinusHours(12),
        reviewedAt: nowMinusHours(11),
        publishedAt: nowMinusHours(11),
        scheduledAt: null,
        deletedAt: null,
        revision: 2,
      },
      {
        id: 'article-football',
        slug: 'national-team-victory',
        title: {
          ru: 'Сборная одержала волевую победу в отборочном матче',
          kk: 'Құрама іріктеу матчінде ерік-жігермен жеңіске жетті',
        },
        excerpt: {
          ru: 'Команда отыгралась со счета 0:2 и забила победный мяч на последних минутах.',
          kk: 'Команда 0:2 есебінен оралып, соңғы минуттарда жеңіс добын соқты.',
        },
        body: {
          ru: 'Национальная сборная провела один из самых ярких матчей квалификационного цикла.\n\nПосле неудачного старта команда переломила ход встречи и вырвала победу в компенсированное время.',
          kk: 'Ұлттық құрама іріктеу цикліндегі ең жарқын матчтардың бірін өткізді.\n\nСәтсіз басталған ойыннан кейін команда кездесудің барысын өзгертіп, қосымша уақытта жеңісті жұлып алды.',
        },
        seoTitle: {
          ru: 'Сборная Казахстана вырвала победу в драматичном матче',
          kk: 'Қазақстан құрамасы драмалық матчта жеңісті жұлып алды',
        },
        seoDescription: {
          ru: 'Ключевые моменты волевой победы национальной сборной.',
          kk: 'Ұлттық құраманың ерік-жігерлі жеңісінің негізгі сәттері.',
        },
        mainImage: '/news/sport-football.png',
        gallery: ['/news/sport-football.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['sport'],
        tags: ['футбол', 'сборная', 'спорт'],
        sourceName: '',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: true,
        views: 21340,
        readMinutes: 2,
        createdAt: nowMinusHours(34),
        updatedAt: nowMinusHours(9),
        submittedAt: nowMinusHours(10),
        reviewedAt: nowMinusHours(9),
        publishedAt: nowMinusHours(9),
        scheduledAt: null,
        deletedAt: null,
        revision: 2,
      },
      {
        id: 'article-ai-services',
        slug: 'digital-services-ai',
        title: {
          ru: 'Госуслуги переходят на искусственный интеллект: что изменится',
          kk: 'Мемлекеттік қызметтер жасанды интеллектке көшуде: не өзгереді',
        },
        excerpt: {
          ru: 'Новый цифровой помощник будет обрабатывать обращения граждан и подсказывать нужные документы.',
          kk: 'Жаңа цифрлық көмекші азаматтардың өтініштерін өңдеп, қажетті құжаттарды ұсынады.',
        },
        body: {
          ru: 'Правительство представило обновленную платформу электронных услуг с AI-помощником.\n\nСервис будет отвечать на типовые обращения, помогать со сбором документов и распределять запросы по ведомствам.',
          kk: 'Үкімет AI-көмекшісі бар электрондық қызметтердің жаңартылған платформасын таныстырды.\n\nСервис типтік өтініштерге жауап беріп, құжаттарды жинауға көмектеседі және сұраныстарды ведомстволарға бөледі.',
        },
        seoTitle: {
          ru: 'Как AI меняет государственные сервисы Казахстана',
          kk: 'AI Қазақстанның мемлекеттік сервистерін қалай өзгертеді',
        },
        seoDescription: {
          ru: 'Новый AI-помощник в госуслугах: возможности, риски и этапы запуска.',
          kk: 'Мемқызметтердегі жаңа AI-көмекші: мүмкіндіктері, тәуекелдері және іске қосу кезеңдері.',
        },
        mainImage: '/news/tech-digital.png',
        gallery: ['/news/tech-digital.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['business-economy'],
        tags: ['ai', 'govtech', 'цифровизация'],
        sourceName: '',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 6410,
        readMinutes: 5,
        createdAt: nowMinusHours(40),
        updatedAt: nowMinusHours(15),
        submittedAt: nowMinusHours(16),
        reviewedAt: nowMinusHours(15),
        publishedAt: nowMinusHours(15),
        scheduledAt: null,
        deletedAt: null,
        revision: 2,
      },
      {
        id: 'article-festival',
        slug: 'national-culture-festival',
        title: {
          ru: 'Фестиваль национальной музыки собрал рекордное число зрителей',
          kk: 'Ұлттық музыка фестиваліне рекордтық көрермен жиналды',
        },
        excerpt: {
          ru: 'На главной сцене выступили признанные мастера и молодые исполнители народных инструментов.',
          kk: 'Басты сахнада танымал шеберлер мен халық аспаптарында ойнайтын жас орындаушылар өнер көрсетті.',
        },
        body: {
          ru: 'Ежегодный фестиваль национальной музыки прошел с аншлагом.\n\nОрганизаторы уже заявили, что в следующем году расширят программу и пригласят исполнителей из соседних стран.',
          kk: 'Жыл сайынғы ұлттық музыка фестивалі аншлагпен өтті.\n\nҰйымдастырушылар келесі жылы бағдарламаны кеңейтіп, көрші елдердің орындаушыларын шақыратынын мәлімдеді.',
        },
        seoTitle: {
          ru: 'Фестиваль национальной музыки прошел при аншлаге',
          kk: 'Ұлттық музыка фестивалі аншлагпен өтті',
        },
        seoDescription: {
          ru: 'Главные итоги музыкального фестиваля и планы организаторов на следующий год.',
          kk: 'Музыкалық фестивальдің негізгі қорытындылары мен ұйымдастырушылардың келесі жылға жоспары.',
        },
        mainImage: '/news/culture-dombra.png',
        gallery: ['/news/culture-dombra.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['culture-events'],
        tags: ['музыка', 'фестиваль', 'культура'],
        sourceName: '',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 4870,
        readMinutes: 3,
        createdAt: nowMinusHours(48),
        updatedAt: nowMinusHours(18),
        submittedAt: nowMinusHours(20),
        reviewedAt: nowMinusHours(19),
        publishedAt: nowMinusHours(19),
        scheduledAt: null,
        deletedAt: null,
        revision: 1,
      },
      {
        id: 'article-road-safety',
        slug: 'highway-safety-measures',
        title: {
          ru: 'На трассах усилили меры безопасности из-за непогоды',
          kk: 'Қолайсыз ауа райына байланысты тас жолдарда қауіпсіздік шаралары күшейтілді',
        },
        excerpt: {
          ru: 'Водителей просят быть внимательнее: на отдельных участках ограничена скорость движения.',
          kk: 'Жүргізушілерден абай болу сұралады: кей учаскелерде жылдамдық шектелді.',
        },
        body: {
          ru: 'Дорожные службы перевели работу в усиленный режим из-за ухудшения погодных условий.\n\nНа ряде участков ограничена скорость, а спасательные бригады переведены в состояние повышенной готовности.',
          kk: 'Жол қызметтері ауа райының нашарлауына байланысты күшейтілген режимге көшті.\n\nБірқатар учаскеде жылдамдық шектеліп, құтқару бригадалары жоғары дайындыққа келтірілді.',
        },
        seoTitle: {
          ru: 'Непогода на трассах: меры безопасности для водителей',
          kk: 'Тас жолдардағы қолайсыз ауа райы: жүргізушілерге арналған қауіпсіздік шаралары',
        },
        seoDescription: {
          ru: 'Какие ограничения ввели на трассах и что рекомендуют экстренные службы.',
          kk: 'Тас жолдарда қандай шектеулер енгізілді және төтенше қызметтер не ұсынады.',
        },
        mainImage: '/news/incident-road.png',
        gallery: ['/news/incident-road.png'],
        videoUrls: [],
        authorId,
        reviewerId: editorId,
        categories: ['society'],
        tags: ['трасса', 'безопасность', 'погода'],
        sourceName: 'Комитет по ЧС',
        sourceUrl: '',
        status: 'published',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 9120,
        readMinutes: 2,
        createdAt: nowMinusHours(52),
        updatedAt: nowMinusHours(16),
        submittedAt: nowMinusHours(17),
        reviewedAt: nowMinusHours(16),
        publishedAt: nowMinusHours(16),
        scheduledAt: null,
        deletedAt: null,
        revision: 1,
      },
      {
        id: 'article-wind-park',
        slug: 'green-energy-investment',
        title: {
          ru: 'В стране запустят крупнейший ветропарк в Центральной Азии',
          kk: 'Елде Орталық Азиядағы ең ірі жел паркі іске қосылады',
        },
        excerpt: {
          ru: 'Проект обеспечит чистой энергией сотни тысяч домохозяйств и создаст новые рабочие места.',
          kk: 'Жоба жүздеген мың үй шаруашылығын таза энергиямен қамтып, жаңа жұмыс орындарын ашады.',
        },
        body: {
          ru: 'Строительство нового ветропарка должно стать одним из крупнейших зеленых проектов региона.\n\nИнвесторы рассчитывают на долгосрочные контракты и рост доли возобновляемой генерации в энергобалансе.',
          kk: 'Жаңа жел паркінің құрылысы аймақтағы ең ірі жасыл жобалардың біріне айналмақ.\n\nИнвесторлар ұзақмерзімді келісімшарттарға және жаңартылатын энергия үлесінің өсуіне сенеді.',
        },
        seoTitle: {
          ru: 'Крупнейший ветропарк в Центральной Азии построят в Казахстане',
          kk: 'Орталық Азиядағы ең ірі жел паркі Қазақстанда салынады',
        },
        seoDescription: {
          ru: 'Что известно о новом ветропарке и его влиянии на энергорынок.',
          kk: 'Жаңа жел паркі және оның энергия нарығына әсері туралы не белгілі.',
        },
        mainImage: '/news/energy-oil.png',
        gallery: ['/news/energy-oil.png'],
        videoUrls: [],
        authorId,
        reviewerId: null,
        categories: ['business-economy', 'analytics'],
        tags: ['энергетика', 'ветропарк', 'инвестиции'],
        sourceName: '',
        sourceUrl: '',
        status: 'scheduled',
        previousStatus: null,
        showOnHome: true,
        featured: false,
        breaking: false,
        views: 5230,
        readMinutes: 4,
        createdAt: nowMinusHours(3),
        updatedAt: nowMinusHours(1),
        submittedAt: nowMinusHours(1),
        reviewedAt: nowMinusHours(1),
        publishedAt: null,
        scheduledAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
        deletedAt: null,
        revision: 1,
      },
      {
        id: 'article-author-draft',
        slug: 'startup-ecosystem-growth',
        title: {
          ru: 'Технопарк привлек рекордные инвестиции в местные стартапы',
          kk: 'Технопарк жергілікті стартаптарға рекордтық инвестиция тартты',
        },
        excerpt: {
          ru: 'Молодые IT-компании получают доступ к менторам, грантам и международным акселераторам.',
          kk: 'Жас IT-компаниялар менторларға, гранттарға және халықаралық акселераторларға қол жеткізеді.',
        },
        body: {
          ru: 'Национальный технопарк отчитался о рекордном объеме инвестиций в стартапы.\n\nАвторы материала готовят обновление после публикации подробных отраслевых данных.',
          kk: 'Ұлттық технопарк стартаптарға тартылған рекордтық инвестиция көлемі туралы есеп берді.\n\nМатериал авторлары салалық деректер жарияланғаннан кейін жаңарту дайындап жатыр.',
        },
        seoTitle: {
          ru: 'Стартапы Казахстана привлекли рекордные инвестиции',
          kk: 'Қазақстан стартаптары рекордтық инвестиция тартты',
        },
        seoDescription: {
          ru: 'Черновик материала о росте стартап-экосистемы и новых инвестициях.',
          kk: 'Стартап-экожүйенің өсуі және жаңа инвестициялар туралы материалдың черновигі.',
        },
        mainImage: '/news/tech-digital.png',
        gallery: [],
        videoUrls: [],
        authorId,
        reviewerId: null,
        categories: ['business-economy'],
        tags: ['стартап', 'инвестиции', 'it'],
        sourceName: '',
        sourceUrl: '',
        status: 'draft',
        previousStatus: null,
        showOnHome: false,
        featured: false,
        breaking: false,
        views: 0,
        readMinutes: 4,
        createdAt: nowMinusHours(6),
        updatedAt: nowMinusHours(1),
        submittedAt: null,
        reviewedAt: null,
        publishedAt: null,
        scheduledAt: null,
        deletedAt: null,
        revision: 1,
      },
    ],
    audit: [
      {
        id: 'audit-seed-1',
        entityType: 'article',
        entityId: 'article-astana-summit',
        action: 'published',
        actorId: editorId,
        actorName: 'Редактор Эхо Алматы',
        summary: 'Материал опубликован после редакторской проверки.',
        timestamp: nowMinusHours(4),
      },
      {
        id: 'audit-seed-2',
        entityType: 'auth',
        entityId: editorId,
        action: 'seeded',
        actorId: adminId,
        actorName: 'Администратор Эхо Алматы',
        summary: 'Создан демонстрационный редакторский аккаунт.',
        timestamp: nowMinusHours(24),
      },
    ],
    subscribers: [],
  }
}
